In [102]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import re

Scarpe data from the website

First dataset

Scarpe tutorial 
https://chihacknight.org/blog/2014/11/26/an-intro-to-web-scraping-with-python.html

In [91]:
url = "http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_Dinov_021808_ConsumerPriceIndex"
r = requests.get(url)
data = r.text
soup = BeautifulSoup(data,"xml")
table = soup.find_all("table")[2]
rows = table.find_all('tr')[1:]
data = {
    "Year" : [],
    "Jan" : [],
    "Feb" : [],
    "Mar" : [],
    "Apr" : [],
    "May" : [],
    "Jun" : [],
    "Jul" : [],
    "Aug" : [],
    "Sep" : [],
    "Oct" : [],
    "Nov" : [],
    "Dec" : [],
    "CPI_Item" : []
}

for row in rows:
    cols = row.find_all('td')
    data["Year"].append( cols[0].get_text() )
    data["Jan"].append( cols[1].get_text() )
    data["Feb"].append( cols[2].get_text() )
    data["Mar"].append( cols[3].get_text() )
    data["Apr"].append( cols[4].get_text() )
    data["May"].append( cols[5].get_text() )
    data["Jun"].append( cols[6].get_text() )
    data["Jul"].append( cols[7].get_text() )
    data["Aug"].append( cols[8].get_text() )
    data["Sep"].append( cols[9].get_text() )
    data["Oct"].append( cols[10].get_text() )
    data["Nov"].append( cols[11].get_text() )
    data["Dec"].append( cols[12].get_text() )
    data["CPI_Item"].append( cols[13].get_text() )

SORC1 = pd.DataFrame( data , columns = list(data))

SORC1

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,CPI_Item
0,1980,26.698,27.701,28.15,28.433,28.96,30.931,31.513,31.569,31.755,30.89,30.381,30.967,Electricity_500_KWH\n
1,1981,31.552,32.097,32.473,32.848,33.1,34.962,35.744,36.496,36.273,34.872,34.919,34.96,Electricity_500_KWH\n
2,1982,36.006,36.086,36.741,36.799,36.438,38.047,38.403,38.471,38.265,37.388,36.655,37.074,Electricity_500_KWH\n
3,1983,37.184,37.306,37.393,37.117,37.424,39.216,39.507,39.592,39.578,38.781,38.325,38.188,Electricity_500_KWH\n
4,1984,38.6,38.832,39.066,39.487,39.539,41.635,42.406,43.35,40.801,39.441,38.935,38.626,Electricity_500_KWH\n
5,1985,38.975,39.107,39.312,39.485,39.468,41.169,41.172,41.497,40,40.25,39.752,39.754,Electricity_500_KWH\n
6,1986,40.223,40.85,40.662,40.259,40.334,41.887,42.138,42.157,42.165,40.211,39.89,39.813,Electricity_500_KWH\n
7,1987,40.022,40.01,40.208,40.075,40.088,42.462,42.686,42.636,42.26,40.328,40.206,40.233,Electricity_500_KWH\n
8,1988,40.195,40.286,40.2,39.737,39.218,41.43,41.509,41.63,41.727,40.857,40.387,40.717,Electricity_500_KWH\n
9,1989,40.828,40.563,40.72,41.018,40.985,42.596,42.825,42.824,42.844,41.398,41.226,41.618,Electricity_500_KWH\n
10,1990,41.663,42.004,41.87,42.052,42.061,43.665,43.531,43.484,43.605,42.296,42.125,42.145,Electricity_500_KWH\n
11,1991,43.226,43.413,43.467,42.961,43.547,44.652,45.015,44.834,45.083,44.168,43.745,44.303,Electricity_500_KWH\n
12,1992,44.501,44.352,45.101,44.963,45.311,46.708,46.862,46.608,47.115,45.938,45.602,46.779,Electricity_500_KWH\n
13,1993,46.959,46.286,46.835,47.015,47.19,48.535,48.68,49.692,49.751,48.821,48.243,48.248,Electricity_500_KWH\n
14,1994,48.2,48.403,47.95,47.64,47.948,49.385,49.505,49.622,49.514,48.83,48.783,48.554,Electricity_500_KWH\n
15,1995,48.874,48.523,48.746,48.131,48.888,50.448,50.552,50.395,49.735,49.472,49.209,48.571,Electricity_500_KWH\n
16,1996,48.538,48.542,49.137,49.221,49.232,49.178,50.483,50.753,50.789,49.913,49.181,49.231,Electricity_500_KWH\n
17,1997,49.245,49.434,49.516,49.271,49.399,50.838,50.79,50.543,50.695,49.278,48.836,48.131,Electricity_500_KWH\n
18,1998,46.401,45.728,45.659,45.739,45.846,46.647,46.757,46.439,46.073,45.458,45.259,45.16,Electricity_500_KWH\n
19,1999,45.061,45.171,45.233,45.179,45.233,45.994,46.298,46.235,46.267,45.736,45.378,45.375,Electricity_500_KWH\n
20,2000,45.207,45.542,45.598,45.524,45.509,46.638,47.396,47.218,47.197,46.57,46.229,46.404,Electricity_500_KWH\n
21,2001,47.472,47.419,47.72,47.725,48.105,49.836,50.09,49.702,49.419,48.693,48.143,48.324,Electricity_500_KWH\n
22,2002,47.868,47.736,47.851,47.368,47.539,48.7,48.684,48.665,48.59,48.087,47.61,47.65,Electricity_500_KWH\n
23,2003,47.663,47.832,48.275,48.81,49.168,49.883,50.226,50.497,50.563,49.738,48.988,49.004,Electricity_500_KWH\n
24,2004,49.159,49.412,49.166,49.353,49.646,51.063,51.388,51.519,51.343,50.27,49.94,49.927,Electricity_500_KWH\n
25,2005,50.847,50.853,51.146,51.263,51.979,53.651,53.924,54.11,54.324,54.06,54.843,54.672,Electricity_500_KWH\n
26,2006,57.223,57.133,57.156,57.27,57.462,59.457,59.621,59.565,59.568,58.332,57.532,57.738,Electricity_500_KWH\n
27,2007,59.043,59.047,59.297,59.175,59.779,61.568,61.562,61.368,61.457,60.885,60.418,60.52,Electricity_500_KWH\n
28,1980,1.11,1.186,1.23,1.242,1.244,1.246,1.247,1.243,1.231,1.223,1.222,1.231,Gas_per_Gallon\n
29,1981,1.269,1.353,1.388,1.381,1.37,1.362,1.353,1.348,1.358,1.353,1.351,1.348,Gas_per_Gallon\n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,2006,2.607,2.556,2.568,2.599,2.508,2.543,2.459,2.543,2.508,2.542,2.564,2.606,GroundBeef_1_lb\n
297,2007,2.63,2.639,2.628,2.676,2.766,2.739,2.734,2.695,2.744,2.705,2.738,2.702,GroundBeef_1_lb\n
298,1980,0.501,0.507,0.502,0.507,0.504,0.503,0.511,0.507,0.511,0.514,0.519,0.519,Bread_1_lb_white\n
299,1981,0.531,0.533,0.538,0.519,0.525,0.523,0.521,0.519,0.524,0.521,0.527,0.521,Bread_1_lb_white\n
300,1982,0.537,0.534,0.526,0.526,0.529,0.525,0.534,0.534,0.536,0.534,0.534,0.537,Bread_1_lb_white\n
301,1983,0.541,0.544,0.544,0.538,0.542,0.542,0.544,0.539,0.536,0.535,0.547,0.547,Bread_1_lb_white\n
302,1984,0.543,0.541,0.542,0.536,0.541,0.542,0.541,0.543,0.539,0.54,0.543,0.544,Bread_1_lb_white\n
303,1985,0.551,0.544,0.544,0.544,0.542,0.546,0.556,0.553,0.561,0.566,0.564,0.568,Bread_1_lb_white\n
304,1986,0.566,0.563,0.56,0.561,0.562,0.569,0.564,0.57,0.566,0.565,0.564,0.566,Bread_1_lb_white\n
305,1987,0.544,0.539,0.541,0.542,0.54,0.533,0.544,0.546,0.551,0.559,0.559,0.571,Bread_1_lb_white\n
306,1988,0.586,0.586,0.587,0.595,0.598,0.601,0.602,0.619,0.636,0.642,0.645,0.657,Bread_1_lb_white\n
307,1989,0.653,0.652,0.654,0.655,0.655,0.664,0.671,0.674,0.671,0.674,0.676,0.688,Bread_1_lb_white\n
308,1990,0.689,0.701,0.68,0.686,0.678,0.687,0.685,0.713,0.7,0.706,0.71,0.7,Bread_1_lb_white\n
309,1991,0.705,0.701,0.702,0.701,0.705,0.705,0.7,0.714,0.717,0.72,0.731,0.717,Bread_1_lb_white\n
310,1992,0.726,0.73,0.747,0.746,0.752,0.757,0.771,0.776,0.756,0.752,0.747,0.738,Bread_1_lb_white\n
311,1993,0.748,0.751,0.742,0.744,0.752,0.752,0.762,0.745,0.748,0.75,0.771,0.76,Bread_1_lb_white\n
312,1994,0.768,0.756,0.755,0.765,0.765,0.761,0.759,0.753,0.776,0.756,0.766,0.748,Bread_1_lb_white\n
313,1995,0.767,0.767,0.775,0.776,0.768,0.781,0.789,0.797,0.808,0.809,0.821,0.837,Bread_1_lb_white\n
314,1996,0.86,0.858,0.852,0.865,0.869,0.886,0.889,0.915,0.886,0.873,0.88,0.875,Bread_1_lb_white\n
315,1997,0.862,0.858,0.855,0.855,0.854,0.874,0.872,0.872,0.885,0.899,0.897,0.884,Bread_1_lb_white\n
316,1998,0.855,0.86,0.853,0.863,0.866,0.859,0.867,0.869,0.86,0.849,0.855,0.866,Bread_1_lb_white\n
317,1999,0.872,0.88,0.883,0.897,0.886,0.885,0.893,0.884,0.878,0.889,0.899,0.899,Bread_1_lb_white\n
318,2000,0.907,0.924,0.924,0.927,0.915,0.915,0.935,0.923,0.918,0.934,0.953,0.987,Bread_1_lb_white\n
319,2001,0.982,0.994,1.02,1.008,0.995,0.989,0.987,0.991,0.996,1.01,1.012,1.005,Bread_1_lb_white\n
320,2002,1.001,1.008,1.012,1.005,1.012,1.011,1.015,1.012,1.016,1.015,1.054,1.026,Bread_1_lb_white\n
321,2003,1.042,1.048,1.042,1.047,1.001,0.961,1.002,0.996,0.994,0.969,0.953,0.954,Bread_1_lb_white\n
322,2004,0.946,0.943,0.947,0.974,0.96,0.979,0.985,0.996,0.985,0.972,0.976,0.97,Bread_1_lb_white\n
323,2005,0.997,0.982,1.002,1.004,1.086,1.09,1.067,1.06,1.052,1.043,1.055,1.046,Bread_1_lb_white\n
324,2006,1.046,1.029,1.04,1.072,1.086,1.074,1.071,1.088,1.083,1.097,1.143,1.137,Bread_1_lb_white\n
325,2007,1.153,1.168,1.161,1.201,1.192,1.193,1.209,1.21,1.212,1.274,1.235,1.28,Bread_1_lb_white\n

Change it into tidy data

In [97]:
SORC2 = pd.melt(SORC1, ["Year","CPI_Item"], var_name = "Month", value_name = "CPI_Value")
SORC2

        Year                CPI_Item Month CPI_Value
0      1980    Electricity_500_KWH\n   Jan   26.698
1      1981    Electricity_500_KWH\n   Jan   31.552
2      1982    Electricity_500_KWH\n   Jan   36.006
3      1983    Electricity_500_KWH\n   Jan   37.184
4      1984    Electricity_500_KWH\n   Jan     38.6
5      1985    Electricity_500_KWH\n   Jan   38.975
6      1986    Electricity_500_KWH\n   Jan   40.223
7      1987    Electricity_500_KWH\n   Jan   40.022
8      1988    Electricity_500_KWH\n   Jan   40.195
9      1989    Electricity_500_KWH\n   Jan   40.828
10     1990    Electricity_500_KWH\n   Jan   41.663
11     1991    Electricity_500_KWH\n   Jan   43.226
12     1992    Electricity_500_KWH\n   Jan   44.501
13     1993    Electricity_500_KWH\n   Jan   46.959
14     1994    Electricity_500_KWH\n   Jan     48.2
15     1995    Electricity_500_KWH\n   Jan   48.874
16     1996    Electricity_500_KWH\n   Jan   48.538
17     1997    Electricity_500_KWH\n   Jan   49.245
18     1998    Electricity_500_KWH\n   Jan   46.401
19     1999    Electricity_500_KWH\n   Jan   45.061
20     2000    Electricity_500_KWH\n   Jan   45.207
21     2001    Electricity_500_KWH\n   Jan   47.472
22     2002    Electricity_500_KWH\n   Jan   47.868
23     2003    Electricity_500_KWH\n   Jan   47.663
24     2004    Electricity_500_KWH\n   Jan   49.159
25     2005    Electricity_500_KWH\n   Jan   50.847
26     2006    Electricity_500_KWH\n   Jan   57.223
27     2007    Electricity_500_KWH\n   Jan   59.043
28     1980         Gas_per_Gallon\n   Jan     1.11
29     1981         Gas_per_Gallon\n   Jan    1.269
...      ...                     ...   ...       ...
3882   2006        GroundBeef_1_lb\n   Dec    2.606
3883   2007        GroundBeef_1_lb\n   Dec    2.702
3884   1980       Bread_1_lb_white\n   Dec    0.519
3885   1981       Bread_1_lb_white\n   Dec    0.521
3886   1982       Bread_1_lb_white\n   Dec    0.537
3887   1983       Bread_1_lb_white\n   Dec    0.547
3888   1984       Bread_1_lb_white\n   Dec    0.544
3889   1985       Bread_1_lb_white\n   Dec    0.568
3890   1986       Bread_1_lb_white\n   Dec    0.566
3891   1987       Bread_1_lb_white\n   Dec    0.571
3892   1988       Bread_1_lb_white\n   Dec    0.657
3893   1989       Bread_1_lb_white\n   Dec    0.688
3894   1990       Bread_1_lb_white\n   Dec      0.7
3895   1991       Bread_1_lb_white\n   Dec    0.717
3896   1992       Bread_1_lb_white\n   Dec    0.738
3897   1993       Bread_1_lb_white\n   Dec     0.76
3898   1994       Bread_1_lb_white\n   Dec    0.748
3899   1995       Bread_1_lb_white\n   Dec    0.837
3900   1996       Bread_1_lb_white\n   Dec    0.875
3901   1997       Bread_1_lb_white\n   Dec    0.884
3902   1998       Bread_1_lb_white\n   Dec    0.866
3903   1999       Bread_1_lb_white\n   Dec    0.899
3904   2000       Bread_1_lb_white\n   Dec    0.987
3905   2001       Bread_1_lb_white\n   Dec    1.005
3906   2002       Bread_1_lb_white\n   Dec    1.026
3907   2003       Bread_1_lb_white\n   Dec    0.954
3908   2004       Bread_1_lb_white\n   Dec     0.97
3909   2005       Bread_1_lb_white\n   Dec    1.046
3910   2006       Bread_1_lb_white\n   Dec    1.137
3911   2007       Bread_1_lb_white\n   Dec     1.28

[3912 rows x 4 columns]

Scrape Second dataset

In [220]:
url = "http://wiki.socr.umich.edu/index.php/SOCR_Data_Dinov_021808_ConsumerPriceIndex3Way"
r = requests.get(url)
data = r.text
soup = BeautifulSoup(data,"xml")
table = soup.find_all("table")[0]
rows = table.find_all('tr')[1:]
data = {
    "Year" : [],
    "CPI_Item" : [],
    "Month" : [],
    "CPI_Value" : []
}

for row in rows:
    cols = row.find_all('td')
    data["Year"].append( cols[0].get_text() )
    data["CPI_Item"].append( cols[1].get_text() )
    data["Month"].append( cols[2].get_text() )
    data["CPI_Value"].append( cols[3].get_text() )

SORC3 = pd.DataFrame( data , columns = list(data))
SORC3

#data cleaning with Regular Expression
p = re.compile("\n")
SORC3.loc[:,"CPI_Value"] = SORC3.loc[:,"CPI_Value"].str.replace(p, "").astype(float)
SORC3

        Year       CPI_Item  Month  CPI_Value
0      1981           Food    Jan      91.400
1      1981           Food    Feb      92.200
2      1981           Food    Mar      92.700
3      1981           Food    Apr      92.900
4      1981           Food    May      92.800
5      1981           Food    Jun      93.200
6      1981           Food    Jul      94.100
7      1981           Food    Aug      94.500
8      1981           Food    Sep      94.700
9      1981           Food    Oct      94.500
10     1981           Food    Nov      94.400
11     1981           Food    Dec      94.600
12     1982           Food    Jan      95.700
13     1982           Food    Feb      96.500
14     1982           Food    Mar      96.400
15     1982           Food    Apr      96.700
16     1982           Food    May      97.300
17     1982           Food    Jun      98.000
18     1982           Food    Jul      98.200
19     1982           Food    Aug      97.900
20     1982           Food    Sep      98.000
21     1982           Food    Oct      97.800
22     1982           Food    Nov      97.600
23     1982           Food    Dec      97.600
24     1983           Food    Jan      98.200
25     1983           Food    Feb      98.500
26     1983           Food    Mar      99.100
27     1983           Food    Apr      99.600
28     1983           Food    May      99.700
29     1983           Food    Jun      99.600
...      ...            ...    ...        ...
1266   2005    MedicalCare    Jul     324.100
1267   2005    MedicalCare    Aug     323.900
1268   2005    MedicalCare    Sep     324.600
1269   2005    MedicalCare    Oct     326.200
1270   2005    MedicalCare    Nov     328.100
1271   2005    MedicalCare    Dec     328.400
1272   2006    MedicalCare    Jan     329.500
1273   2006    MedicalCare    Feb     332.100
1274   2006    MedicalCare    Mar     333.800
1275   2006    MedicalCare    Apr     334.700
1276   2006    MedicalCare    May     335.600
1277   2006    MedicalCare    Jun     336.000
1278   2006    MedicalCare    Jul     337.000
1279   2006    MedicalCare    Aug     337.700
1280   2006    MedicalCare    Sep     338.300
1281   2006    MedicalCare    Oct     339.300
1282   2006    MedicalCare    Nov     340.100
1283   2006    MedicalCare    Dec     340.100
1284   2007    MedicalCare    Jan     343.510
1285   2007    MedicalCare    Feb     346.457
1286   2007    MedicalCare    Mar     347.172
1287   2007    MedicalCare    Apr     348.225
1288   2007    MedicalCare    May     349.087
1289   2007    MedicalCare    Jun     349.510
1290   2007    MedicalCare    Jul     351.643
1291   2007    MedicalCare    Aug     352.961
1292   2007    MedicalCare    Sep     353.723
1293   2007    MedicalCare    Oct     355.653
1294   2007    MedicalCare    Nov     357.041
1295   2007    MedicalCare    Dec     357.661

[1296 rows x 4 columns]

Merge dataset

In [284]:
SORC = pd.concat([SORC2,SORC3])
SORC.loc[:,"CPI_Value"] = SORC.loc[:,"CPI_Value"].astype(float)
SORC

        Year                CPI_Item  Month  CPI_Value
0      1980    Electricity_500_KWH\n    Jan     26.698
1      1981    Electricity_500_KWH\n    Jan     31.552
2      1982    Electricity_500_KWH\n    Jan     36.006
3      1983    Electricity_500_KWH\n    Jan     37.184
4      1984    Electricity_500_KWH\n    Jan     38.600
5      1985    Electricity_500_KWH\n    Jan     38.975
6      1986    Electricity_500_KWH\n    Jan     40.223
7      1987    Electricity_500_KWH\n    Jan     40.022
8      1988    Electricity_500_KWH\n    Jan     40.195
9      1989    Electricity_500_KWH\n    Jan     40.828
10     1990    Electricity_500_KWH\n    Jan     41.663
11     1991    Electricity_500_KWH\n    Jan     43.226
12     1992    Electricity_500_KWH\n    Jan     44.501
13     1993    Electricity_500_KWH\n    Jan     46.959
14     1994    Electricity_500_KWH\n    Jan     48.200
15     1995    Electricity_500_KWH\n    Jan     48.874
16     1996    Electricity_500_KWH\n    Jan     48.538
17     1997    Electricity_500_KWH\n    Jan     49.245
18     1998    Electricity_500_KWH\n    Jan     46.401
19     1999    Electricity_500_KWH\n    Jan     45.061
20     2000    Electricity_500_KWH\n    Jan     45.207
21     2001    Electricity_500_KWH\n    Jan     47.472
22     2002    Electricity_500_KWH\n    Jan     47.868
23     2003    Electricity_500_KWH\n    Jan     47.663
24     2004    Electricity_500_KWH\n    Jan     49.159
25     2005    Electricity_500_KWH\n    Jan     50.847
26     2006    Electricity_500_KWH\n    Jan     57.223
27     2007    Electricity_500_KWH\n    Jan     59.043
28     1980         Gas_per_Gallon\n    Jan      1.110
29     1981         Gas_per_Gallon\n    Jan      1.269
...      ...                     ...    ...        ...
1266   2005             MedicalCare    Jul     324.100
1267   2005             MedicalCare    Aug     323.900
1268   2005             MedicalCare    Sep     324.600
1269   2005             MedicalCare    Oct     326.200
1270   2005             MedicalCare    Nov     328.100
1271   2005             MedicalCare    Dec     328.400
1272   2006             MedicalCare    Jan     329.500
1273   2006             MedicalCare    Feb     332.100
1274   2006             MedicalCare    Mar     333.800
1275   2006             MedicalCare    Apr     334.700
1276   2006             MedicalCare    May     335.600
1277   2006             MedicalCare    Jun     336.000
1278   2006             MedicalCare    Jul     337.000
1279   2006             MedicalCare    Aug     337.700
1280   2006             MedicalCare    Sep     338.300
1281   2006             MedicalCare    Oct     339.300
1282   2006             MedicalCare    Nov     340.100
1283   2006             MedicalCare    Dec     340.100
1284   2007             MedicalCare    Jan     343.510
1285   2007             MedicalCare    Feb     346.457
1286   2007             MedicalCare    Mar     347.172
1287   2007             MedicalCare    Apr     348.225
1288   2007             MedicalCare    May     349.087
1289   2007             MedicalCare    Jun     349.510
1290   2007             MedicalCare    Jul     351.643
1291   2007             MedicalCare    Aug     352.961
1292   2007             MedicalCare    Sep     353.723
1293   2007             MedicalCare    Oct     355.653
1294   2007             MedicalCare    Nov     357.041
1295   2007             MedicalCare    Dec     357.661

[5208 rows x 4 columns]

In [286]:
SORC = pd.pivot_table(SORC, index = ["Year", "Month"], values='CPI_Value', columns='CPI_Item').reset_index().rename_axis(None, axis=1)
SORC

,Year,Month,Apples_Red_1_lb,Bananas_1_lb,Bread_1_lb_white,Chicken_1_lb,Eggs_GradeA_1_dozen,Electricity_500_KWH,Food,Gas_per_Gallon,GroundBeef_1_lb,Housing,Lettuce_Iceberg_1_lb,MedicalCare,Milk_Whole_0.5_gallon,OrangeJuice_1_lb,Tomatos_1_lb,Transportation
0,1980,Apr,0.634,0.353,0.507,0.638,0.797,28.433,NaN,1.242,1.818,NaN,0.565,NaN,1.024,1.199,0.634,NaN
1,1980,Aug,0.807,0.335,0.507,0.751,0.907,31.569,NaN,1.243,1.842,NaN,0.397,NaN,1.058,1.158,0.646,NaN
2,1980,Dec,0.503,0.349,0.519,0.760,1.031,30.967,NaN,1.231,1.863,NaN,0.483,NaN,1.092,1.122,0.662,NaN
3,1980,Feb,0.574,0.345,0.507,0.673,0.774,27.701,NaN,1.186,1.843,NaN,0.369,NaN,1.020,1.271,0.586,NaN
4,1980,Jan,0.554,0.319,0.501,0.699,0.879,26.698,NaN,1.110,1.821,NaN,0.354,NaN,1.015,1.243,0.703,NaN
5,1980,Jul,0.753,0.332,0.511,0.710,0.776,31.513,NaN,1.247,1.780,NaN,0.387,NaN,1.053,1.153,0.683,NaN
6,1980,Jun,0.701,0.348,0.503,0.640,0.731,30.931,NaN,1.246,1.793,NaN,0.462,NaN,1.052,1.190,0.745,NaN
7,1980,Mar,0.593,0.355,0.502,0.655,0.812,28.150,NaN,1.230,1.855,NaN,0.385,NaN,1.019,1.201,0.642,NaN
8,1980,May,0.663,0.357,0.504,0.628,0.737,28.960,NaN,1.244,1.807,NaN,0.561,NaN,1.044,1.162,0.737,NaN
9,1980,Nov,0.496,0.339,0.519,0.766,0.917,30.381,NaN,1.222,1.852,NaN,0.522,NaN,1.084,1.147,0.603,NaN
10,1980,Oct,0.570,0.335,0.514,0.792,0.867,30.890,NaN,1.223,1.861,NaN,0.441,NaN,1.067,1.134,0.764,NaN
11,1980,Sep,0.702,0.335,0.511,0.791,0.898,31.755,NaN,1.231,1.865,NaN,0.500,NaN,1.062,1.170,0.679,NaN
12,1981,Apr,NaN,NaN,NaN,NaN,NaN,NaN,92.900,NaN,NaN,87.700,NaN,80.800,NaN,NaN,NaN,91.600
13,1981,Aug,NaN,NaN,NaN,NaN,NaN,NaN,94.500,NaN,NaN,92.300,NaN,84.300,NaN,NaN,NaN,94.400
14,1981,Dec,NaN,NaN,NaN,NaN,NaN,NaN,94.600,NaN,NaN,94.000,NaN,87.300,NaN,NaN,NaN,96.400
15,1981,Feb,NaN,NaN,NaN,NaN,NaN,NaN,92.200,NaN,NaN,86.500,NaN,79.600,NaN,NaN,NaN,90.100
16,1981,Jan,NaN,NaN,NaN,NaN,NaN,NaN,91.400,NaN,NaN,85.900,NaN,78.700,NaN,NaN,NaN,88.100
17,1981,Jul,NaN,NaN,NaN,NaN,NaN,NaN,94.100,NaN,NaN,91.500,NaN,83.200,NaN,NaN,NaN,94.000
18,1981,Jun,NaN,NaN,NaN,NaN,NaN,NaN,93.200,NaN,NaN,90.000,NaN,82.100,NaN,NaN,NaN,93.100
19,1981,Mar,NaN,NaN,NaN,NaN,NaN,NaN,92.700,NaN,NaN,87.000,NaN,80.200,NaN,NaN,NaN,91.000
20,1981,May,NaN,NaN,NaN,NaN,NaN,NaN,92.800,NaN,NaN,88.800,NaN,81.400,NaN,NaN,NaN,92.400
21,1981,Nov,NaN,NaN,NaN,NaN,NaN,NaN,94.400,NaN,NaN,93.700,NaN,86.800,NaN,NaN,NaN,96.200
22,1981,Oct,NaN,NaN,NaN,NaN,NaN,NaN,94.500,NaN,NaN,93.500,NaN,85.800,NaN,NaN,NaN,95.600
23,1981,Sep,NaN,NaN,NaN,NaN,NaN,NaN,94.700,NaN,NaN,93.500,NaN,84.900,NaN,NaN,NaN,94.900
24,1981,Apr,0.529,0.377,0.519,0.734,0.904,32.848,NaN,1.381,1.783,NaN,0.441,NaN,1.116,1.416,1.201,NaN
25,1981,Aug,0.662,0.351,0.519,0.752,0.868,36.496,NaN,1.348,1.795,NaN,0.553,NaN,1.117,1.457,0.659,NaN
26,1981,Dec,0.617,0.364,0.521,0.700,0.966,34.960,NaN,1.348,1.806,NaN,0.646,NaN,1.129,1.413,0.642,NaN
27,1981,Feb,0.504,0.366,0.533,0.759,0.924,32.097,NaN,1.353,1.832,NaN,0.429,NaN,1.106,1.241,1.016,NaN
28,1981,Jan,0.512,0.343,0.531,0.749,0.943,31.552,NaN,1.269,1.856,NaN,0.441,NaN,1.104,1.141,0.792,NaN
29,1981,Jul,0.577,0.341,0.521,0.767,0.860,35.744,NaN,1.353,1.764,NaN,0.499,NaN,1.118,1.428,0.614,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
630,2006,Jun,1.053,0.511,1.074,1.055,1.242,59.457,NaN,2.963,2.543,NaN,0.848,NaN,NaN,1.886,1.457,NaN
631,2006,Mar,0.935,0.508,1.040,1.047,1.302,57.156,NaN,2.444,2.568,NaN,0.815,NaN,NaN,1.895,1.649,NaN
632,2006,May,1.021,0.514,1.086,1.034,1.206,57.462,NaN,2.993,2.508,NaN,0.967,NaN,NaN,1.912,1.543,NaN
633,2006,Nov,1.089,0.498,1.143,1.049,1.354,57.532,NaN,2.287,2.564,NaN,0.850,NaN,NaN,2.160,1.784,NaN
634,2006,Oct,1.138,0.489,1.097,1.038,1.257,58.332,NaN,2.319,2.542,NaN,0.873,NaN,NaN,2.015,2.188,NaN
635,2006,Sep,1.256,0.479,1.083,1.063,1.254,59.568,NaN,2.637,2.508,NaN,0.953,NaN,NaN,2.013,1.908,NaN
636,2007,Apr,NaN,NaN,NaN,NaN,NaN,NaN,201.292,NaN,NaN,208.541,NaN,348.225,NaN,NaN,NaN,185.231
637,2007,Aug,NaN,NaN,NaN,NaN,NaN,NaN,204.289,NaN,NaN,211.098,NaN,352.961,NaN,NaN,NaN,184.480
638,2007,Dec,NaN,NaN,NaN,NaN,NaN,NaN,206.936,NaN,NaN,210.933,NaN,357.661,NaN,NaN,NaN,189.984
639,2007,Feb,NaN,NaN,NaN,NaN,NaN,NaN,200.402,NaN,NaN,207.177,NaN,346.457,NaN,NaN,NaN,174.799
640,2007,Jan,NaN,NaN,NaN,NaN,NaN,NaN,199.198,NaN,NaN,206.057,NaN,343.510,NaN,NaN,NaN,174.463
641,2007,Jul,NaN,NaN,NaN,NaN,NaN,NaN,203.533,NaN,NaN,211.286,NaN,351.643,NaN,NaN,NaN,187.690
642,2007,Jun,NaN,NaN,NaN,NaN,NaN,NaN,202.885,NaN,NaN,210.649,NaN,349.510,NaN,NaN,NaN,189.064
643,2007,Mar,NaN,NaN,NaN,NaN,NaN,NaN,200.869,NaN,NaN,208.080,NaN,347.172,NaN,NaN,NaN,180.346
644,2007,May,NaN,NaN,NaN,NaN,NaN,NaN,202.225,NaN,NaN,208.902,NaN,349.087,NaN,NaN,NaN,189.961
645,2007,Nov,NaN,NaN,NaN,NaN,NaN,NaN,206.563,NaN,NaN,210.745,NaN,357.041,NaN,NaN,NaN,190.677
646,2007,Oct,NaN,NaN,NaN,NaN,NaN,NaN,206.124,NaN,NaN,210.701,NaN,355.653,NaN,NaN,NaN,184.952
647,2007,Sep,NaN,NaN,NaN,NaN,NaN,NaN,205.279,NaN,NaN,210.865,NaN,353.723,NaN,NaN,NaN,184.532
648,2007,Apr,1.104,0.517,1.201,1.115,1.616,59.175,NaN,2.909,2.676,NaN,0.986,NaN,NaN,2.517,1.630,NaN
649,2007,Aug,1.194,0.506,1.210,1.145,1.634,61.368,NaN,2.833,2.695,NaN,0.879,NaN,NaN,2.568,1.485,NaN
650,2007,Dec,1.121,0.525,1.280,1.166,2.099,60.520,NaN,3.069,2.702,NaN,0.949,NaN,NaN,2.528,2.147,NaN
651,2007,Feb,1.072,0.507,1.168,1.039,1.746,59.047,NaN,2.333,2.639,NaN,0.920,NaN,NaN,2.414,1.644,NaN
652,2007,Jan,1.034,0.505,1.153,1.033,1.549,59.043,NaN,2.321,2.630,NaN,0.926,NaN,NaN,2.314,1.621,NaN
653,2007,Jul,1.184,0.509,1.209,1.130,1.502,61.562,NaN,3.013,2.734,NaN,0.849,NaN,NaN,2.538,1.486,NaN
654,2007,Jun,1.130,0.512,1.193,1.134,1.373,61.568,NaN,3.100,2.739,NaN,0.856,NaN,NaN,2.512,1.510,NaN
655,2007,Mar,1.068,0.510,1.161,1.064,1.634,59.297,NaN,2.639,2.628,NaN,0.915,NaN,NaN,2.463,1.555,NaN
656,2007,May,1.112,0.503,1.192,1.118,1.504,59.779,NaN,3.176,2.766,NaN,0.879,NaN,NaN,2.456,1.685,NaN
657,2007,Nov,1.103,0.515,1.235,1.161,1.862,60.418,NaN,3.118,2.738,NaN,0.988,NaN,NaN,2.561,1.851,NaN
658,2007,Oct,1.083,0.508,1.274,1.135,1.771,60.885,NaN,2.843,2.705,NaN,1.066,NaN,NaN,2.574,1.649,NaN
659,2007,Sep,1.178,0.505,1.212,1.142,1.825,61.457,NaN,2.839,2.744,NaN,0.927,NaN,NaN,2.590,1.496,NaN